# Generated by Django 5.2.16 on 2026-07-30 09:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ragione_sociale', models.CharField(max_length=255)),
                ('partita_iva', models.CharField(max_length=20, unique=True)),
                ('referente', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cliente',
                'ordering': ('ragione_sociale',),
            },
        ),
        migrations.CreateModel(
            name='Commessa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codice', models.CharField(max_length=80, unique=True)),
                ('descrizione', models.TextField()),
                ('ore_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('data_inizio', models.DateField()),
                ('data_fine_prevista', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('APERTA', 'Aperta'), ('CHIUSA', 'Chiusa')], default='APERTA', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commesse', to='projects.cliente')),
            ],
            options={
                'db_table': 'commessa',
                'ordering': ('-data_inizio', 'codice'),
            },
        ),
        migrations.CreateModel(
            name='Assegnazione',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ore_previste', models.PositiveIntegerField()),
                ('ruolo_commessa', models.CharField(choices=[('CONSULENTE', 'Consulente'), ('PROJECT_MANAGER', 'Project Manager')], default='CONSULENTE', max_length=30)),
                ('stato', models.CharField(choices=[('ATTIVA', 'Attiva'), ('CONCLUSA', 'Conclusa')], default='ATTIVA', max_length=20)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('consulente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assegnazioni', to=settings.AUTH_USER_MODEL)),
                ('commessa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assegnazioni', to='projects.commessa')),
            ],
            options={
                'db_table': 'assegnazione',
                'ordering': ('commessa__codice', 'consulente__last_name'),
            },
        ),
        migrations.CreateModel(
            name='TariffaAssegnazione',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_attivita', models.CharField(choices=[('FORMAZIONE', 'Formazione'), ('CONSULENZA', 'Consulenza')], max_length=20)),
                ('tariffa_oraria', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valida_dal', models.DateField()),
                ('assegnazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariffe', to='projects.assegnazione')),
                ('creata_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariffe_create', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tariffa_assegnazione',
                'ordering': ('assegnazione', 'tipo_attivita', '-valida_dal'),
            },
        ),
        migrations.AddConstraint(
            model_name='commessa',
            constraint=models.CheckConstraint(condition=models.Q(('data_fine_prevista__isnull', True), ('data_fine_prevista__gte', models.F('data_inizio')), _connector='OR'), name='commessa_fine_non_precede_inizio'),
        ),
        migrations.AddConstraint(
            model_name='assegnazione',
            constraint=models.UniqueConstraint(condition=models.Q(('stato', 'ATTIVA')), fields=('consulente', 'commessa'), name='uq_assegnazione_attiva_consulente_commessa'),
        ),
        migrations.AddConstraint(
            model_name='assegnazione',
            constraint=models.CheckConstraint(condition=models.Q(('data_fine__isnull', True), ('data_fine__gte', models.F('data_inizio')), _connector='OR'), name='assegnazione_fine_non_precede_inizio'),
        ),
        migrations.AddConstraint(
            model_name='tariffaassegnazione',
            constraint=models.UniqueConstraint(fields=('assegnazione', 'tipo_attivita', 'valida_dal'), name='uq_tariffa_assegnazione_tipo_data'),
        ),
        migrations.AddConstraint(
            model_name='tariffaassegnazione',
            constraint=models.CheckConstraint(condition=models.Q(('tariffa_oraria__gte', 0)), name='tariffa_oraria_non_negativa'),
        ),
    ]
