# Generated by Django 5.2.17 on 2026-09-09 09:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True)),
                ('stato', models.CharField(choices=[('DA_FARE', 'Da fare'), ('IN_CORSO', 'In corso'), ('COMPLETATA', 'Completata')], default='DA_FARE', max_length=20)),
                ('priorita', models.CharField(choices=[('BASSA', 'Bassa'), ('NORMALE', 'Normale'), ('ALTA', 'Alta')], default='NORMALE', max_length=20)),
                ('data_inizio', models.DateField(blank=True, null=True)),
                ('data_scadenza', models.DateField(blank=True, db_index=True, null=True)),
                ('completato_il', models.DateTimeField(blank=True, null=True)),
                ('assegnato_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_assegnati', to=settings.AUTH_USER_MODEL)),
                ('commessa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='projects.commessa')),
                ('creato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_creati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task',
                'ordering': ('data_scadenza', '-priorita', 'titolo'),
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('testo', models.TextField()),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commenti_task', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='tasks.task')),
            ],
            options={
                'db_table': 'task_comment',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['commessa', 'stato'], name='idx_task_commessa_stato'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assegnato_a', 'stato'], name='idx_task_assegnato_stato'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('data_inizio__isnull', True), ('data_scadenza__isnull', True), ('data_scadenza__gte', models.F('data_inizio')), _connector='OR'), name='task_scadenza_non_precede_inizio'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'created_at'], name='idx_task_comment_data'),
        ),
    ]
