# Generated by Django 5.2.17 on 2026-09-17 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0004_alter_fasecommessa_ordine'),
        ('tasks', '0003_fase_obbligatoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fase',
            field=models.ForeignKey(help_text='Fase operativa obbligatoria della commessa.', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='phases.fasecommessa'),
        ),
    ]
