# Generated by Django 5.2.17 on 2026-09-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_business_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ruolo',
            field=models.CharField(choices=[('ADMIN', 'Admin LEF'), ('CONSULENTE', 'Consulente / Team esecutivo'), ('RESP_CONSULENZA', 'Responsabile Business Unit'), ('AMMINISTRAZIONE', 'Amministrazione'), ('COMMERCIALE', 'Commerciale'), ('DIREZIONE_GENERALE', 'Direzione Generale')], default='CONSULENTE', max_length=30),
        ),
    ]
