services:
  reminder:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
    restart: unless-stopped
    command: >
      sh -c "while true;
      do python manage.py invia_promemoria_timesheet;
      sleep 3600;
      done"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
