# Generated by Django 5.2.17 on 2026-09-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0003_fase_date_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasecommessa',
            name='ordine',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
