# Generated by Django 5.2.17 on 2026-09-17 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documento_fase'),
        ('phases', '0004_alter_fasecommessa_ordine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocommessa',
            name='fase',
            field=models.ForeignKey(blank=True, help_text='Fase di lavoro; vuota solo per documenti generali di commessa.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documenti', to='phases.fasecommessa'),
        ),
    ]
