# Generated by Django 5.2.17 on 2026-09-17 13:23

import apps.documents.models
import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentocommessa_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocommessa',
            name='file',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/app/private_media')), upload_to=apps.documents.models.percorso_documento),
        ),
    ]
