# Generated by Django 5.2.6 on 2026-09-28 13:30

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_documentocommessa_privato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentocommessa",
            name="file",
            field=models.FileField(
                max_length=500,
                storage=apps.documents.models.get_documenti_storage,
                upload_to=apps.documents.models.percorso_documento,
            ),
        ),
    ]
