# Generated by Django 5.2.17 on 2026-09-07 10:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiornoPianificato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('ore_pianificate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('modificata_da_admin', models.BooleanField(default=False)),
                ('assegnazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giorni_pianificati', to='projects.assegnazione')),
                ('inserita_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pianificazioni_inserite', to=settings.AUTH_USER_MODEL)),
                ('ultima_modifica_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pianificazioni_modificate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'giorno_pianificato',
                'ordering': ('data', 'assegnazione__consulente__last_name', 'assegnazione__commessa__codice'),
                'indexes': [models.Index(fields=['data'], name='idx_pianificazione_data'), models.Index(fields=['assegnazione', 'data'], name='idx_pianificazione_ass_data')],
                'constraints': [models.UniqueConstraint(fields=('assegnazione', 'data'), name='uq_giorno_pianificato_assegnazione_data'), models.CheckConstraint(condition=models.Q(('ore_pianificate__gte', 1), ('ore_pianificate__lte', 8)), name='giorno_pianificato_ore_1_8')],
            },
        ),
    ]
