# Generated by Django 5.2.16 on 2026-07-30 09:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazionePromemoria',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('giorno_invio', models.PositiveSmallIntegerField(default=25)),
                ('ora_invio', models.TimeField()),
                ('attiva', models.BooleanField(default=True)),
                ('solo_assenza_totale_ore', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aggiornata_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurazioni_promemoria_aggiornate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'configurazione_promemoria',
            },
        ),
        migrations.CreateModel(
            name='Importazione',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome_file', models.CharField(max_length=255)),
                ('file_hash', models.CharField(blank=True, max_length=128)),
                ('stato', models.CharField(choices=[('VALIDAZIONE', 'In validazione'), ('PRONTA', 'Pronta'), ('COMPLETATA', 'Completata'), ('ERRORE', 'Errore')], max_length=30)),
                ('righe_totali', models.PositiveIntegerField(default=0)),
                ('righe_valide', models.PositiveIntegerField(default=0)),
                ('righe_errore', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('avviata_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importazioni_avviate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'importazione',
            },
        ),
        migrations.CreateModel(
            name='ErroreImportazione',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_riga', models.PositiveIntegerField()),
                ('campo', models.CharField(blank=True, max_length=100)),
                ('codice_errore', models.CharField(blank=True, max_length=50)),
                ('messaggio', models.TextField()),
                ('dati_riga', models.JSONField()),
                ('importazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errori', to='operations.importazione')),
            ],
            options={
                'db_table': 'errore_importazione',
                'ordering': ('numero_riga', 'id'),
            },
        ),
        migrations.CreateModel(
            name='InvioPromemoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anno', models.PositiveSmallIntegerField()),
                ('mese', models.PositiveSmallIntegerField()),
                ('stato', models.CharField(choices=[('INVIATO', 'Inviato'), ('ERRORE', 'Errore')], max_length=20)),
                ('data_tentativo', models.DateTimeField()),
                ('errore', models.TextField(blank=True)),
                ('configurazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invii', to='operations.configurazionepromemoria')),
                ('consulente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promemoria_ricevuti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invio_promemoria',
            },
        ),
        migrations.CreateModel(
            name='PeriodoMensile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anno', models.PositiveSmallIntegerField()),
                ('mese', models.PositiveSmallIntegerField()),
                ('stato', models.CharField(choices=[('APERTO', 'Aperto'), ('CHIUSO', 'Chiuso')], default='APERTO', max_length=20)),
                ('data_chiusura', models.DateTimeField(blank=True, null=True)),
                ('data_riapertura', models.DateTimeField(blank=True, null=True)),
                ('forzatura_tariffe_mancanti', models.BooleanField(default=False)),
                ('motivazione_forzatura', models.TextField(blank=True)),
                ('chiuso_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodi_chiusi', to=settings.AUTH_USER_MODEL)),
                ('riaperto_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodi_riaperti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'periodo_mensile',
                'ordering': ('-anno', '-mese'),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entita', models.CharField(max_length=80)),
                ('entita_id', models.UUIDField()),
                ('azione', models.CharField(max_length=50)),
                ('valore_precedente', models.JSONField(blank=True, null=True)),
                ('valore_nuovo', models.JSONField(blank=True, null=True)),
                ('motivazione', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventi_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['entita', 'entita_id'], name='idx_audit_entita_id')],
            },
        ),
        migrations.AddConstraint(
            model_name='configurazionepromemoria',
            constraint=models.CheckConstraint(condition=models.Q(('giorno_invio__gte', 1), ('giorno_invio__lte', 28)), name='promemoria_giorno_tra_1_e_28'),
        ),
        migrations.AddConstraint(
            model_name='inviopromemoria',
            constraint=models.UniqueConstraint(fields=('consulente', 'anno', 'mese'), name='uq_promemoria_consulente_periodo'),
        ),
        migrations.AddConstraint(
            model_name='inviopromemoria',
            constraint=models.CheckConstraint(condition=models.Q(('mese__gte', 1), ('mese__lte', 12)), name='promemoria_mese_valido'),
        ),
        migrations.AddConstraint(
            model_name='periodomensile',
            constraint=models.UniqueConstraint(fields=('anno', 'mese'), name='uq_periodo_anno_mese'),
        ),
        migrations.AddConstraint(
            model_name='periodomensile',
            constraint=models.CheckConstraint(condition=models.Q(('mese__gte', 1), ('mese__lte', 12)), name='periodo_mese_valido'),
        ),
    ]
