# Generated by Django 5.2.16 on 2026-07-30 09:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RigaOre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(db_index=True)),
                ('tipo_attivita', models.CharField(choices=[('FORMAZIONE', 'Formazione'), ('CONSULENZA', 'Consulenza')], max_length=20)),
                ('ore', models.PositiveSmallIntegerField()),
                ('nota', models.TextField(blank=True)),
                ('modificata_da_admin', models.BooleanField(default=False)),
                ('bloccata_per_consulente', models.BooleanField(default=False)),
                ('versione', models.PositiveIntegerField(default=1)),
                ('assegnazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='righe_ore', to='projects.assegnazione')),
                ('inserita_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='righe_ore_inserite', to=settings.AUTH_USER_MODEL)),
                ('ultima_modifica_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='righe_ore_modificate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'riga_ore',
                'ordering': ('-data', '-created_at'),
                'indexes': [models.Index(fields=['assegnazione', 'data'], name='idx_ore_assegnazione_data')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ore__gt', 0)), name='riga_ore_maggiore_zero')],
            },
        ),
        migrations.CreateModel(
            name='SpesaTrasferta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(db_index=True)),
                ('categoria', models.CharField(choices=[('VIAGGIO', 'Viaggio'), ('VITTO', 'Vitto'), ('ALLOGGIO', 'Alloggio'), ('ALTRO', 'Altro')], max_length=20)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('nota', models.TextField(blank=True)),
                ('modificata_da_admin', models.BooleanField(default=False)),
                ('bloccata_per_consulente', models.BooleanField(default=False)),
                ('versione', models.PositiveIntegerField(default=1)),
                ('assegnazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spese_trasferta', to='projects.assegnazione')),
                ('inserita_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spese_inserite', to=settings.AUTH_USER_MODEL)),
                ('ultima_modifica_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spese_modificate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spesa_trasferta',
                'ordering': ('-data', '-created_at'),
                'indexes': [models.Index(fields=['assegnazione', 'data'], name='idx_spesa_assegnazione_data')],
                'constraints': [models.CheckConstraint(condition=models.Q(('importo__gt', 0)), name='spesa_importo_maggiore_zero')],
            },
        ),
    ]
