# Generated by Django 5.2.17 on 2026-09-20 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rigaore',
            name='approvata_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='righe_ore_approvate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rigaore',
            name='data_approvazione',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rigaore',
            name='nota_approvazione',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rigaore',
            name='stato_approvazione',
            field=models.CharField(choices=[('IN_ATTESA', 'Da approvare'), ('APPROVATA', 'Approvata'), ('RIFIUTATA', 'Rifiutata')], db_index=True, default='IN_ATTESA', max_length=20),
        ),
        migrations.AddField(
            model_name='spesatrasferta',
            name='approvata_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spese_approvate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spesatrasferta',
            name='data_approvazione',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spesatrasferta',
            name='nota_approvazione',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spesatrasferta',
            name='stato_approvazione',
            field=models.CharField(choices=[('IN_ATTESA', 'Da approvare'), ('APPROVATA', 'Approvata'), ('RIFIUTATA', 'Rifiutata')], db_index=True, default='IN_ATTESA', max_length=20),
        ),
    ]
