# Generated by Django 5.2.17 on 2026-09-09 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('TASK_ASSIGNED', 'Nuova attività assegnata'), ('TASK_COMMENTED', 'Nuovo commento'), ('TASK_DUE_SOON', 'Attività in scadenza'), ('TASK_OVERDUE', 'Attività scaduta')], db_index=True, max_length=30)),
                ('titolo', models.CharField(max_length=255)),
                ('messaggio', models.TextField(blank=True)),
                ('letta_il', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('data_riferimento', models.DateField(blank=True, null=True)),
                ('chiave_evento', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('attore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifiche_generate', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to='tasks.task')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['destinatario', 'letta_il'], name='idx_notification_user_read'), models.Index(fields=['task', 'tipo'], name='idx_notification_task_type')],
            },
        ),
    ]
